### ISSUE TITLE
Merge cli options with options from settings

### ISSUE THREAD

**Issue by Sebobo** [bwaidelich/Wwwision.ImportService#6]
E.g. it would be helpful to be able to provide the `filePath` for the `FileDataSource` as command line option.

I'm not sure exactly where this change would be best made, or if this was anyway planned somehow.

**Comment by bwaidelich** [comment]
Added with ae93ac46d7153bf571fed34b2212c37406c561ac (for version 3.0.0). Thanks for the idea
